package com.pakrinha.khmerphonetic

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The phone must type exactly what the browser types.
 *
 * golden.tsv is generated by tools/build_android.mjs by running the web app's
 * own convert() over every romanization key, every ordered pair of keys, the
 * spellings from the README, and 20,000 random strings. If the Kotlin port ever
 * drifts from the JavaScript, this fails.
 */
class EngineTest {

    private fun golden(): List<Pair<String, String>> {
        val stream = checkNotNull(javaClass.classLoader?.getResourceAsStream("golden.tsv")) {
            "golden.tsv missing — run: npm run build:android"
        }
        return stream.bufferedReader().useLines { lines ->
            lines.mapNotNull { line ->
                val tab = line.indexOf('\t')
                if (tab <= 0) null else line.substring(0, tab) to line.substring(tab + 1)
            }.toList()
        }
    }

    @Test
    fun `conversion matches the web engine`() {
        val cases = golden()
        assertTrue("golden.tsv looks empty", cases.size > 20_000)

        var mismatches = 0
        val examples = StringBuilder()
        for ((input, expected) in cases) {
            val actual = PhoneticEngine.convert(input)
            if (actual != expected) {
                mismatches++
                if (mismatches <= 10) {
                    examples.append("\n  \"$input\" -> got \"$actual\", web says \"$expected\"")
                }
            }
        }
        assertEquals("$mismatches of ${cases.size} differ:$examples", 0, mismatches)
    }

    @Test
    fun `known spellings convert correctly`() {
        assertEquals("សួស្តី", PhoneticEngine.convert("suastei"))
        assertEquals("ខ្ញុំ", PhoneticEngine.convert("khnhom"))
        assertEquals("បាទ", PhoneticEngine.convert("baadd"))
        assertEquals("កម្ពុជា", PhoneticEngine.convert("ka.mpujaa"))
        assertEquals("ម៉ោង", PhoneticEngine.convert("m*aong"))
    }

    @Test
    fun `capitals select second-series consonants`() {
        assertEquals("ដ", PhoneticEngine.convert("d"))
        assertEquals("ឌ", PhoneticEngine.convert("D"))
        assertEquals("ន", PhoneticEngine.convert("n"))
        assertEquals("ណ", PhoneticEngine.convert("N"))
        assertEquals("ឡ", PhoneticEngine.convert("L"))
    }

    @Test
    fun `a period breaks a cluster and stacking can be turned off`() {
        assertEquals("ក្ក", PhoneticEngine.convert("kk"))
        assertEquals("កក", PhoneticEngine.convert("k.k"))
        assertEquals("កក", PhoneticEngine.convert("kk", autostack = false))
    }

    @Test
    fun `sound skeletons forgive loose spelling`() {
        // The whole point of the fuzzy tier: these must key to the same shape.
        val canonical = Suggestions.qskel("suosdei")
        assertEquals(canonical, Suggestions.qskel("sousdey"))
        assertEquals(canonical, Suggestions.qskel("suastei"))
        assertEquals("8sd8", Suggestions.vskel("ousdei"))
    }
}
