package com.pakrinha.khmerphonetic

/**
 * GENERATED FILE - do not edit by hand.
 *   regenerate with:  npm run build:android
 *   source of truth:  the romanization maps in index.html
 *
 * The maps below are lifted verbatim from the web app, so the phone types what
 * the browser types. PhoneticEngine.convert() is the port of the loop that
 * walks them; EngineTest checks the two against each other.
 */
object PhoneticScheme {

    const val COENG = "្"

    /** Consonants. These are the tokens that stack with coeng when adjacent. */
    val CONS: Map<String, String> = mapOf(
        "k" to "ក",
        "kh" to "ខ",
        "g" to "គ",
        "gh" to "ឃ",
        "ng" to "ង",
        "ch" to "ច",
        "chh" to "ឆ",
        "j" to "ជ",
        "jh" to "ឈ",
        "ny" to "ញ",
        "nh" to "ញ",
        "d" to "ដ",
        "TH" to "ឋ",
        "D" to "ឌ",
        "DH" to "ឍ",
        "N" to "ណ",
        "t" to "ត",
        "th" to "ថ",
        "dd" to "ទ",
        "dh" to "ធ",
        "n" to "ន",
        "b" to "ប",
        "ph" to "ផ",
        "p" to "ព",
        "bh" to "ភ",
        "m" to "ម",
        "y" to "យ",
        "r" to "រ",
        "l" to "ល",
        "v" to "វ",
        "w" to "វ",
        "s" to "ស",
        "h" to "ហ",
        "L" to "ឡ",
        "q" to "អ",
    )

    /** Independent vowels, all typed with a leading apostrophe. */
    val INDEP: Map<String, String> = mapOf(
        "'e" to "ឯ",
        "'ai" to "ឰ",
        "'o" to "ឱ",
        "'au" to "ឳ",
        "'ri" to "ឫ",
        "'rii" to "ឬ",
        "'li" to "ឭ",
        "'lii" to "ឮ",
        "'q" to "ឥ",
        "'qi" to "ឦ",
        "'qu" to "ឧ",
        "'quu" to "ឩ",
    )

    /** Dependent vowels. "a" is the inherent vowel and emits nothing. */
    val VOW: Map<String, String> = mapOf(
        "aa" to "ា",
        "a" to "",
        "i" to "ិ",
        "ii" to "ី",
        "ei" to "ី",
        "eu" to "ឹ",
        "euu" to "ឺ",
        "u" to "ុ",
        "uu" to "ូ",
        "ou" to "ូ",
        "ua" to "ួ",
        "oe" to "ើ",
        "aeu" to "ើ",
        "oea" to "ឿ",
        "ie" to "ៀ",
        "e" to "េ",
        "ae" to "ែ",
        "eae" to "ែ",
        "ai" to "ៃ",
        "ey" to "ៃ",
        "ao" to "ោ",
        "o" to "ោ",
        "oa" to "ោ",
        "au" to "ៅ",
        "ov" to "ៅ",
        "am" to "ាំ",
        "aM" to "ាំ",
        "um" to "ុំ",
        "om" to "ុំ",
        "ah" to "ះ",
        "eah" to "េះ",
        "oh" to "ោះ",
        "uh" to "ុះ",
        "ih" to "ិះ",
    )

    /** Signs and punctuation. */
    val SIGN: Map<String, String> = mapOf(
        "M" to "ំ",
        "H" to "ះ",
        "'" to "់",
        "^" to "័",
        "~" to "៍",
        "*" to "៉",
        "`" to "៊",
        "." to "",
        "//" to "។",
        "///" to "៕",
        "**" to "ៗ",
        "<<" to "«",
        ">>" to "»",
        "::" to "៖",
    )

    val MAP: Map<String, String> = CONS + INDEP + VOW + SIGN

    /** Which tokens are consonants, for the auto-stacking decision. */
    val IS_CONS: Set<String> = CONS.keys

    /** Longest first: the tokenizer is greedy. */
    val KEYS: List<String> = listOf(
        "'rii",
        "'lii",
        "'quu",
        "chh",
        "'ai",
        "'au",
        "'ri",
        "'li",
        "'qi",
        "'qu",
        "euu",
        "aeu",
        "oea",
        "eae",
        "eah",
        "///",
        "kh",
        "gh",
        "ng",
        "ch",
        "jh",
        "ny",
        "nh",
        "TH",
        "DH",
        "th",
        "dd",
        "dh",
        "ph",
        "bh",
        "'e",
        "'o",
        "'q",
        "aa",
        "ii",
        "ei",
        "eu",
        "uu",
        "ou",
        "ua",
        "oe",
        "ie",
        "ae",
        "ai",
        "ey",
        "ao",
        "oa",
        "au",
        "ov",
        "am",
        "aM",
        "um",
        "om",
        "ah",
        "oh",
        "uh",
        "ih",
        "//",
        "**",
        "<<",
        ">>",
        "::",
        "k",
        "g",
        "j",
        "d",
        "D",
        "N",
        "t",
        "n",
        "b",
        "p",
        "m",
        "y",
        "r",
        "l",
        "v",
        "w",
        "s",
        "h",
        "L",
        "q",
        "a",
        "i",
        "u",
        "e",
        "o",
        "M",
        "H",
        "'",
        "^",
        "~",
        "*",
        "`",
        ".",
    )

    val DIGITS: Map<Char, Char> = mapOf(
        '0' to '០',
        '1' to '១',
        '2' to '២',
        '3' to '៣',
        '4' to '៤',
        '5' to '៥',
        '6' to '៦',
        '7' to '៧',
        '8' to '៨',
        '9' to '៩',
    )
}
