//
//  GENERATED FILE - do not edit by hand.
//    regenerate with:  npm run build:ios
//    source of truth:  the romanization maps in index.html
//
//  Lifted verbatim from the web app so the phone types what the browser types.
//  PhoneticEngine is the port of the loop that walks these; EngineTests checks
//  the two against each other.
//

import Foundation

enum PhoneticScheme {

    static let coeng = "្"

    /// Consonants. These are the tokens that stack with coeng when adjacent.
    static let cons: [String: String] = [
        "k": "ក",
        "kh": "ខ",
        "g": "គ",
        "gh": "ឃ",
        "ng": "ង",
        "ch": "ច",
        "chh": "ឆ",
        "j": "ជ",
        "jh": "ឈ",
        "ny": "ញ",
        "nh": "ញ",
        "d": "ដ",
        "TH": "ឋ",
        "D": "ឌ",
        "DH": "ឍ",
        "N": "ណ",
        "t": "ត",
        "th": "ថ",
        "dd": "ទ",
        "dh": "ធ",
        "n": "ន",
        "b": "ប",
        "ph": "ផ",
        "p": "ព",
        "bh": "ភ",
        "m": "ម",
        "y": "យ",
        "r": "រ",
        "l": "ល",
        "v": "វ",
        "w": "វ",
        "s": "ស",
        "h": "ហ",
        "L": "ឡ",
        "q": "អ",
    ]

    /// Independent vowels, all typed with a leading apostrophe.
    static let indep: [String: String] = [
        "'e": "ឯ",
        "'ai": "ឰ",
        "'o": "ឱ",
        "'au": "ឳ",
        "'ri": "ឫ",
        "'rii": "ឬ",
        "'li": "ឭ",
        "'lii": "ឮ",
        "'q": "ឥ",
        "'qi": "ឦ",
        "'qu": "ឧ",
        "'quu": "ឩ",
    ]

    /// Dependent vowels. "a" is the inherent vowel and emits nothing.
    static let vow: [String: String] = [
        "aa": "ា",
        "a": "",
        "i": "ិ",
        "ii": "ី",
        "ei": "ី",
        "eu": "ឹ",
        "euu": "ឺ",
        "u": "ុ",
        "uu": "ូ",
        "ou": "ូ",
        "ua": "ួ",
        "oe": "ើ",
        "aeu": "ើ",
        "oea": "ឿ",
        "ie": "ៀ",
        "e": "េ",
        "ae": "ែ",
        "eae": "ែ",
        "ai": "ៃ",
        "ey": "ៃ",
        "ao": "ោ",
        "o": "ោ",
        "oa": "ោ",
        "au": "ៅ",
        "ov": "ៅ",
        "am": "ាំ",
        "aM": "ាំ",
        "um": "ុំ",
        "om": "ុំ",
        "ah": "ះ",
        "eah": "េះ",
        "oh": "ោះ",
        "uh": "ុះ",
        "ih": "ិះ",
    ]

    /// Signs and punctuation.
    static let sign: [String: String] = [
        "M": "ំ",
        "H": "ះ",
        "'": "់",
        "^": "័",
        "~": "៍",
        "*": "៉",
        "`": "៊",
        ".": "",
        "//": "។",
        "///": "៕",
        "**": "ៗ",
        "<<": "«",
        ">>": "»",
        "::": "៖",
    ]

    static let map: [String: String] = cons.merging(indep) { a, _ in a }
        .merging(vow) { a, _ in a }
        .merging(sign) { a, _ in a }

    /// Which tokens are consonants, for the auto-stacking decision.
    static let isCons: Set<String> = Set(cons.keys)

    /// Longest first: the tokenizer is greedy.
    static let keys: [String] = [
        "'rii",
        "'lii",
        "'quu",
        "chh",
        "'ai",
        "'au",
        "'ri",
        "'li",
        "'qi",
        "'qu",
        "euu",
        "aeu",
        "oea",
        "eae",
        "eah",
        "///",
        "kh",
        "gh",
        "ng",
        "ch",
        "jh",
        "ny",
        "nh",
        "TH",
        "DH",
        "th",
        "dd",
        "dh",
        "ph",
        "bh",
        "'e",
        "'o",
        "'q",
        "aa",
        "ii",
        "ei",
        "eu",
        "uu",
        "ou",
        "ua",
        "oe",
        "ie",
        "ae",
        "ai",
        "ey",
        "ao",
        "oa",
        "au",
        "ov",
        "am",
        "aM",
        "um",
        "om",
        "ah",
        "oh",
        "uh",
        "ih",
        "//",
        "**",
        "<<",
        ">>",
        "::",
        "k",
        "g",
        "j",
        "d",
        "D",
        "N",
        "t",
        "n",
        "b",
        "p",
        "m",
        "y",
        "r",
        "l",
        "v",
        "w",
        "s",
        "h",
        "L",
        "q",
        "a",
        "i",
        "u",
        "e",
        "o",
        "M",
        "H",
        "'",
        "^",
        "~",
        "*",
        "`",
        ".",
    ]

    static let khmerDigits: [Character: Character] = [
        "0": "០",
        "1": "១",
        "2": "២",
        "3": "៣",
        "4": "៤",
        "5": "៥",
        "6": "៦",
        "7": "៧",
        "8": "៨",
        "9": "៩",
    ]
}
